### ISSUE TITLE
Lecture 1 Notes - Possible Mistake

### ISSUE THREAD

**Issue by DarianNwankwo** [dbindel/cs6210-f19#4]
In the PDF view, page 10, where you discuss different matrix-matrix multiplication methods, I believe the fourth bullet should read:

> j(ij) or j(ki): Each column of C is A multiplied by a column of B

instead of 

> j(ij) or j(ki): Each column of C is A multiplied by a column of C

**Comment by jpryan1** [comment]
Thanks Darian!
